export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "About",
    headline: "",
    description: "Inifinita, a visionary organization dedicated to promoting STEM education and computer literacy among young students. At Inifinita, we believe in the power of knowledge and innovation to shape a better future, and we are committed to nurturing the next generation of thinkers, creators, and problem solvers. Through a diverse array of engaging events such as hackathons, workshops, sky observation programs, and keynote speeches, we strive to ignite a passion for science, technology, engineering, and mathematics in the hearts of the youth. Our mission is to empower students with the tools and skills they need to thrive in an ever-evolving world, and our upcoming robotics workshop is a testament to our unwavering commitment to providing hands-on experiences that inspire and transform young minds.",
    buttonLabel: "Get Started",
    RegLink: "https://docs.google.com/forms/d/e/1FAIpQLSf2eWjqeOYi6tHNw70FSd_aKzCDkZ-QoJEuY1qVv1uBYWkijw/viewform?usp=sf_link",
    imgStart: true,
    img: require("../../images/cover-art.png"),
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
}